### PR TITLE
Vagrant

### PR DESCRIPTION
**Pull request by AaronWitter**
- 10 minute cross platform setup for the software
- uses Trusty Ubuntu 14.04 LTS box

### CODE REVIEW

**Comment by KaneMorgan** [comment]
im getting JAVA_HOME is not correctly defined when I try and run the server

**Comment by AaronWitter** [comment]
try vagrant reload and see if the problem persists.

Make sure you're using the command in the readme to run the server.

**Comment by KaneMorgan** [comment]
the provisioning script installs java 7, I thought we were using java 8?

**Comment by AaronWitter** [comment]
Java 7 was the only one i could get to install at the time, and it ran the tool fine.

Now we've merged your csv branch, you are right, it needs to be java 8. I'll make the change.

**Comment by AaronWitter** [comment]
run `vagrant destroy`

then `vagrant up` to provision a clean machine with java 8

then use the command from the readme to start the server

**Comment by KaneMorgan** [comment]
okay this works now, i think there are a couple of confilcts in the readme, so it may need to be rebased.

**Pull request merged**
