### PR TITLE
Update authenticate path

### PR DESCRIPTION
**Pull request by KaneMorgan**

### CODE REVIEW

**Comment by daniel-western** [comment]
A few initial comments...before I look at the code changes

- the flow looks really good and logical
- choosing the year 2014 from the drop down list and clicking submit reloads the page for 2014 and shows the "no reports for this year" message as expected. but the drop down list select is automatically set back to 2015. The drop down should be consistent with the year presented on screen. I would consider this a bug.. should be easy to fix.
- The Submit Query button should be named something less techy (maybe "Show Reports") and should be consistent in look and feel with the other buttons. Please set the styling to be the same as the others...
- I think the drop down list should be bigger. The text size should be at least as big as the surrounding text (e.g. Select a filing period)
- it looks really weird that the File A Report button is so far to the right. This is especially the case when there are no reports in the list. Can we have it to the left underneath the "Year 2015" text? Or the immediate side of it?
- There is too big a gap between "Year 2015" and the start of the list of the versions. The list is being pushed down by the File Report button, and it looks wierd. On my screen its not even obvious there is a list of reports until I scroll down. The list needs to be brought higher up directly underneath the Year 2015 text
- The version text (e.g. "Version 33") needs to be smaller. It looks strange that its the same size as Year 2015 text. I would say bring this font size and that of the clickable links also down by a -1 or -2 at least.

Im not sure if you were going to do any tweaking to the formatting still and I know that there will be refinement to the look and feel later on, but I think we should make at least the above changes before the show and tell otherwise I suspect it will be commented on.

-

**Comment by daniel-western** [comment]
Im not sure we need a separate AmendView and amend.mustache. The page is going to look almost exactly the same - the only difference I can think of is the text at the top will refer to amending the report. Can we not just use the existing Upload View, or have I missed something?

**Comment by KaneMorgan** [comment]
The reason I originally separated view is mainly there to make some logic easier later on, having it go to a separate end point will make the logic of whether they go to the payment screen a bit easier.  But thinking about it, we can probably still use a single view.

Will address the styling comments soon.

**Comment by daniel-western** [comment]
I definitely agree we need a separate /amend path.. But think we could get away with using the same view

**Comment by KaneMorgan** [comment]
@daniel-western addressed most of your comments

**Pull request merged**
